export const Assets = {
    AssociatedAsset: [
        '/assets/Projects/Associated Asset/1.png',
        '/assets/Projects/Associated Asset/2.png',
        '/assets/Projects/Associated Asset/3.png',
        '/assets/Projects/Associated Asset/4.png',
        '/assets/Projects/Associated Asset/5.png',
        '/assets/Projects/Associated Asset/6.png',
    ],
    BadgesSwap: [
        '/assets/Projects/Badges + Swap/1.png',
        '/assets/Projects/Badges + Swap/2.png',
        '/assets/Projects/Badges + Swap/3.png',
        '/assets/Projects/Badges + Swap/4.png',
        '/assets/Projects/Badges + Swap/5.png',
        '/assets/Projects/Badges + Swap/6.png',
    ],
    DMC: [
        '/assets/Projects/DMC/1.png',
        '/assets/Projects/DMC/2.png',
        '/assets/Projects/DMC/3.png',
        '/assets/Projects/DMC/4.png',
    ],
    Optimization: [
        '/assets/Projects/Optimization/1.png',
        '/assets/Projects/Optimization/2.png',
        '/assets/Projects/Optimization/3.png',
        '/assets/Projects/Optimization/4.png',
    ],
    PasswordRotation: [
        '/assets/Projects/Password Rotation/1.png',
        '/assets/Projects/Password Rotation/2.png',
    ],
    PrivilegeElevation: [
        '/assets/Projects/Privilege Elevation/1.png',
        '/assets/Projects/Privilege Elevation/2.png',
        '/assets/Projects/Privilege Elevation/3.png',
        '/assets/Projects/Privilege Elevation/4.png',
        '/assets/Projects/Privilege Elevation/5.png',
    ],
    PrivilegeThreat: ['/assets/Projects/Privilege Threat/1.png'],
    ResearchRoadmapping: [
        '/assets/Projects/Research - Roadmapping/1.png',
        '/assets/Projects/Research - Roadmapping/2.png',
        '/assets/Projects/Research - Roadmapping/3.png',
        '/assets/Projects/Research - Roadmapping/4.png',
        '/assets/Projects/Research - Roadmapping/5.png',
        '/assets/Projects/Research - Roadmapping/6.png',
        '/assets/Projects/Research - Roadmapping/7.png',
        '/assets/Projects/Research - Roadmapping/8.png',
        '/assets/Projects/Research - Roadmapping/9.png',
        '/assets/Projects/Research - Roadmapping/10.png',
    ],
    ResearchVOC: [
        '/assets/Projects/Research - VOC/1.png',
        '/assets/Projects/Research - VOC/2.png',
        '/assets/Projects/Research - VOC/3.png',
        '/assets/Projects/Research - VOC/4.png',
        '/assets/Projects/Research - VOC/5.png',
        '/assets/Projects/Research - VOC/6.png',
        '/assets/Projects/Research - VOC/7.png',
        '/assets/Projects/Research - VOC/8.png',
        '/assets/Projects/Research - VOC/9.png',
        '/assets/Projects/Research - VOC/10.png',
    ],
};
