import { Assets } from './assets';
import { Project } from './projectModal';

export const projectData: Project[] = [
    {
        mainImage: Assets.AssociatedAsset[5],
        images: Assets.AssociatedAsset,
        title: 'Associated Asset',
        companyName: 'Service Channel',
        metricValue: 30,
        metricDescription: 'Revenue Increase',
        problem: 'Lorem ipsum dolor sit amet...',
        solution: 'Lorem ipsum dolor sit amet...',
    },
    {
        mainImage: Assets.BadgesSwap[0],
        images: Assets.BadgesSwap,
        title: 'Badges + Swap',
        companyName: 'Service Channel',
        metricValue: 30,
        metricDescription: 'Revenue Increase',
        problem: 'Lorem ipsum dolor sit amet...',
        solution: 'Lorem ipsum dolor sit amet...',
    },
    {
        mainImage: Assets.DMC[0],
        images: Assets.DMC,
        title: 'DMC',
        companyName: 'Centrify',
        metricValue: 30,
        metricDescription: 'Revenue Increase',
        problem: 'Lorem ipsum dolor sit amet...',
        solution: 'Lorem ipsum dolor sit amet...',
    },
    {
        mainImage: Assets.Optimization[0],
        images: Assets.Optimization,
        title: 'Optimization',
        companyName: 'Service Channel',
        metricValue: 30,
        metricDescription: 'Revenue Increase',
        problem: 'Lorem ipsum dolor sit amet...',
        solution: 'Lorem ipsum dolor sit amet...',
    },
    {
        mainImage: Assets.PasswordRotation[0],
        images: Assets.PasswordRotation,
        title: 'Password Rotation',
        companyName: 'Centrify',
        metricValue: 30,
        metricDescription: 'Revenue Increase',
        problem: 'Lorem ipsum dolor sit amet...',
        solution: 'Lorem ipsum dolor sit amet...',
    },
    {
        mainImage: Assets.PrivilegeElevation[0],
        images: Assets.PrivilegeElevation,
        title: 'Privilege Elevation',
        companyName: 'Centrify',
        metricValue: 30,
        metricDescription: 'Revenue Increase',
        problem: 'Lorem ipsum dolor sit amet...',
        solution: 'Lorem ipsum dolor sit amet...',
    },
    {
        mainImage: Assets.PrivilegeThreat[0],
        images: Assets.PrivilegeThreat,
        title: 'Privilege Threat',
        companyName: 'Centrify',
        metricValue: 30,
        metricDescription: 'Revenue Increase',
        problem: 'Lorem ipsum dolor sit amet...',
        solution: 'Lorem ipsum dolor sit amet...',
    },
    {
        mainImage: Assets.ResearchRoadmapping[0],
        images: Assets.ResearchRoadmapping,
        title: 'Research Roadmapping',
        companyName: 'Service Channel',
        metricValue: 30,
        metricDescription: 'Revenue Increase',
        problem: 'Lorem ipsum dolor sit amet...',
        solution: 'Lorem ipsum dolor sit amet...',
    },
    {
        mainImage: Assets.ResearchVOC[0],
        images: Assets.ResearchVOC,
        title: 'Research VOC',
        companyName: 'Service Channel',
        metricValue: 30,
        metricDescription: 'Revenue Increase',
        problem: 'Lorem ipsum dolor sit amet...',
        solution: 'Lorem ipsum dolor sit amet...',
    },
];
